# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82744bf6c26bed90ec713b6b0dbd070eb7ac9204764be89ddbbef904d146b9f69dbb4ae996ffaeb09f6f5dd27c68b933a5dce48462dde17b41e0a5271894ea00

test:
  secret_key_base: 79ac74b19481ce899bd42043d49dccf746b2f5b1efd3067cbcd7b53a8a3ddf44f359759e6d278e0b9942ac40f961e302fe71b05bc7aab945a1b7df8fa392eb05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
